name: Lindy Coops
favicon: null
layout_spectrum: 0.3387097
typography_spectrum: 0.4247312
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Lindy Coops
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebf3fd'
    - '#f9d51d'
    - '#c2c5b2'
    - '#7c7433'
    - '#4b4b0f'
  brandStrength: 0.6257658437825739
  lightness: 0.5949821
  saturation: 0.6487455
  rhythmicContrast: 0.3405018
purpose: []
